services:
  server:
    build:
      context: ./server
    container_name: thydo_server
    ports:
      - "8081:8081"
    volumes:
      - './server:/server'
      - '/server/node_modules'
      - './dist:/server/dist'
    environment:
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PGUSER=thydo
      - PGPASSWORD=thydo
      - PGDATABASE=thydo
      - PGHOST=postgres
    networks:
      - default
    command: npm start

  postgres:
    container_name: thydo_postgres
    image: postgres:11.3-alpine
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=thydo
